# Generated by Django 5.1.15 on 2026-09-04 00:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras, espacios, guiones y apóstrofes.', regex="^[a-zA-ZÀ-ÿ\\s\\-']+$")], verbose_name='nombre completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('phone', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Ingresá un número de teléfono válido (dígitos, espacios, guiones, paréntesis).', regex='^\\+?[\\d\\s\\-()]+$')], verbose_name='teléfono')),
                ('document_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El número de documento debe contener solo dígitos.', regex='^\\d+$')], verbose_name='nro. de documento')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PolicyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('description', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'tipo de póliza',
                'verbose_name_plural': 'tipos de póliza',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=50, unique=True, verbose_name='nro. de póliza')),
                ('start_date', models.DateField(verbose_name='fecha de inicio')),
                ('end_date', models.DateField(verbose_name='fecha de vencimiento')),
                ('premium', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='prima')),
                ('status', models.CharField(choices=[('vigente', 'Vigente'), ('vencida', 'Vencida'), ('renovada', 'Renovada')], default='vigente', max_length=20, verbose_name='estado')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='policies.client', verbose_name='cliente')),
                ('policy_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='policies.policytype', verbose_name='tipo de póliza')),
            ],
            options={
                'verbose_name': 'póliza',
                'verbose_name_plural': 'pólizas',
                'ordering': ['-start_date'],
            },
        ),
    ]
